README.md, battery.sh
Added a simple action to uninstall the `smc` tool and the `battery` script (i.e., partially addressing #1). From what I understand of the `setup.sh` scripts, the steps required to uninstall this utility are:
1. reset battery charging
2. remove `smc` and `battery` from `/usr/local/bin`
I am not entirely sure about (1), but I suppose this boils down to setting the `CH0B` and `CH0C` keys back to `00`? Or is there another way to reset these keys to their corresponding defaults?
=> Add uninstall action

battery.sh
On systems where `LaunchAgents` directory does not exist in `~/Library/` (that's what I had on my macOS 12.6), the `create_daemon` (and thus `maintain`) command fails. This PR fixes that by making sure that the parent directory of the `daemon_path` file exist.
=> Ensure daemon file's parent directory exists

battery.sh, setup.sh
These two changes fix issues when using the commandline install: 
* a typing error resulting in a superfluous `calling_user` messing up the folder structure
* `battery.sh` errored out on ^M lineendings (DOS lineendings)
=> minor fixes for errors when using the commandline install

app/modules/battery.js
When I configured to maintain the battery at 60%, I noticed that the discharge message was hard-coded at 80%. This PR replaces it with the actual value.
=> Replace hard-coded value when discharging

battery.sh
This fixes issue #72 
Gives hint if setting after `maintain` is not `stop` or is not a number between 0~100
=> Added checks on user input for maintain action

battery.sh
The proposed change modifies the "create_daemon" function, so that the daemon file is only overwritten if it does not yet exist or the contents have changed. 
This fixes the frequently appearing notification 'Background Items Added' (introduced in macOS 13 Ventura)
This notification occurs, for instance, when the app is restarted or when "battery maintain 80" is executed.
=> Remove the regularly appearing notification 'Background Items Added' (introduced in macOS 13 Ventura)

app/modules/theme.js
As mentioned in #105 the way the battery percentage for the menu tray icon is computed is not correct, the issue mentions `Display percentage 5 based on 46`. The reason for this is that in https://github.com/actuallymentor/battery/blob/848ee9ba175b92e6a75acac8d60e9a956bc7a88f/app/modules/theme.js#L26 the sort is lexicographical resulting in `[0, 10, 100, 15, 20, 25, 30, 35, 40, 45, 5, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]`
This PR fixes #105 using the correct sort and also simplifying the way the percentage is  fetched from the sorted array.
=> Correct way to determine battery percentage icon for the menu tray

app/modules/theme.js, app/package.json
A small refactor of the way the battery percentage icon is selected.
Using `Math.floor` to calculate the "rounded" value.
@igorkulman Inspired by PR #119
Mini test:
```
Display percentage 0 based on 0
Display percentage 0 based on 1
Display percentage 0 based on 4
Display percentage 5 based on 5
Display percentage 5 based on 6
Display percentage 45 based on 49
Display percentage 50 based on 50
Display percentage 50 based on 51
Display percentage 95 based on 99
Display percentage 100 based on 100
```
=> Battery percentage calculated

README.md, app/modules/battery.js
- Move from `icanhasip.com` to `icanhazip.com (Cloudflare)`
- Use https in network checks using the `-k` flag
- Update `README.md`
Resolves #151
=> Use https in network checks

battery.sh
Fix for issue #149 and #128: The percentage set in the CLI is not persistent upon GUI reboot, and reset to 80%. 
**Problem**: On launch of the GUI, the maintain.percentage file is deleted, causing the GUI to recreate the file with default value of 80.
this is caused by the call "battery maintain stop" which deletes the maintain.percentage file. 
This issue is easily reproduced by changing the `battery maintain 70` via CLI, and then launching the GUI. 
**Solution**: Remove the deletion of file maintain.percentage in "battery maintain stop" to keep persistence of any previous setting.
-> I have added the deletion of all config files upon uninstall so default settings are back if the user reinstalls battery. 
**Test**: The solution was tested by changing the value through the CLI, and …
=> CLI GUI compatibility

README.md
Update the README.md FAQ section to include the difference/benefit from Optimized Charging, as described in #136.
It shows that I deleted then re-added whitespace and lines of text -- I didn't touch any of that, maybe because new lines were added it changed?
=> Add a  `README.md` FAQ

battery.sh
When disabling the power adapter, also turn off the MagSafe LED.
When enabling, return it to ~~default state~~ correct state based on max level defined by user.
=> Disable MagSafe LED when disabling power adapter

battery.sh
Fix for #104. Check the argument of the charge command to be a number between 1 and 100.
=> Fix for #104: added integer check for charge command argument

.vscode/settings.json, README.md
Clarify in the README that `brew install battery` does not alone completely install the command line tools.
I expected brew to complete the installation of the command line tools. I couldn't locate the tools anywhere. The README didn't explain clearly that `brew install` creates a macOS app that must be run to complete the command line installation.
I expect many others familiar with typical projects manageable with homebrew to have the same confusion. I made very small edits on two lines in the README to address the confusion.
The homebrew cask could separately be updated to be clearer that it's not just the CLI and that the app needs to be run.
I also fixed a small vscode setting for eslint that has been deprecated since vscode 1.85 (November 2023).
=> README installation clarification for homebrew users expecting `brew install` to finish CLI installation

app/modules/battery.js, battery.sh
It's important to order the paths from the most specific to the most general.
This fixes the issue where binaries installed via Homebrew were ignored.
Also, removed `/opt/homebrew` from the list of paths. Homebrew does not install programs to its root directory.
=> Reorder paths.

battery.sh
This is a draft for the feature request in #214.
Output:
```
./battery.sh voltage 11.55 11.7 
01/17/24-19:47:18 - Keeping voltage between 11.55V and 11.7V
01/17/24-19:47:18 - Battery at 11.55V
01/17/24-19:48:18 - Battery at 11.551V
01/17/24-19:49:18 - Battery at 11.549V
01/17/24-19:49:18 - 🔌🔋 Enabling battery charging
01/17/24-19:49:18 - 🔼🪫 Disabling battery discharging
01/17/24-19:50:18 - Battery at 11.688V
01/17/24-19:51:19 - Battery at 11.704V
01/17/24-19:51:19 - 🔌🪫 Disabling battery charging
01/17/24-19:52:19 - Battery at 11.587V
01/17/24-19:53:19 - Battery at 11.569V
01/17/24-19:54:19 - Battery at 11.566V
```
=> Voltage limit

battery.sh
If the charge is above the threshold when the AC charger is connected (i.e the charger was attached when the battery was above e.g. 80%), turn the MagSafe LED green on the next iteration.
=> Update MagSafe LED if threshold reached when AC charger is connected

battery.sh
I've noticed that because the script only runs every 60 seconds, and my computer usually does more than 
a 1% increase in that time, I'll often end up 1-2% over the limit. 
To fix this, this PR sleeps the script for 20 instead of 60 within 3% of the target.
=> Improve accuracy when stopping charging

battery.sh
This PR:
- adds validation, based on @ksgubanov's work on #228, but slightly fixed
- fixes eternal loops where `disable_discharging` would `disable_charging`, even when called from within `enable_charging`
- fixes some MagSafe light stuff
- adds more verbose logging - this can probably be fixed; it's quite messy, but it's more descriptive than before
- takes accuracy code from #241 and seems to work properly ¯\\\_(ツ)_/¯
- still has issues, but doesn't add any new issues that I know of.
I'm very much open to suggestions. This PR kind of throws everything at trying to fix bugs and so may have made some things a bit messier than they used to be. Having said that, I've been stress-testing this code daily for a while and I've not run into the original issues any longer.
Hope it helps!
=> General bugfixes

battery.sh
**Problem**
`battery maintain_synchronous recover` should launch at login per `~/Library/LaunchAgents/battery.plist`. It fails, however, with the message in logs: _Error: recover is not a valid setting for battery maintain. Please use a number between 0 and 100_. As a result, the policy is not enforced and requires `battery maintain 80` to be entered manually.
**Solution**
Reorder `valid_percentage` and `recover` clauses.
**Evidence**
Before the fix:
```
alex@alex-mbp ~ % battery maintain_synchronous recover
07/08/24-11:59:21 - Error: recover is not a valid setting for battery maintain. Please use a number between 0 and 100
```
With the fix:
```
alex@alex-mbp ~ % battery maintain_synchronous recover
07/08/24-12:03:29 - Debug trail. User: alex, config folder: /Users/alex/.battery, logfile: …
```
=> 🐛 first check for recover setting, then valid_percentage
